name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{hashFiles('**/package-lock.json')}}
          restore-keys: |
            nodeModules-

      - name: Install deps
        run: npm i
        env:
          CI: true

      - name: Lint
        run: npm run lint
        env:
          CI: true

      - name: Build
        run: npm run build
        env:
          CI: true
